# Generated by Django 6.0.6 on 2026-06-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleTable',
            new_name='Students',
        ),
    ]
