# Generated by Django 6.0.6 on 2026-06-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_rename_sampletable_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
